version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: buc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buc
      MYSQL_USER: buc_user
      MYSQL_PASSWORD: buc_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - buc_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # FastAPI Backend
  backend:
    build:
      context: ./FastAPI-Database
      dockerfile: Dockerfile
    container_name: buc_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=buc
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - buc_network
    volumes:
      - ./FastAPI-Database:/app
      - /app/env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ./react-admin
      dockerfile: Dockerfile
    container_name: buc_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - buc_network
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  buc_network:
    driver: bridge 